// Heuristic "AI signals" — tell-tale footprints left by AI coding tools.
// These are clues, not proof: detecting AI-authored code reliably isn't
// possible, so we only surface which tools' footprints we found.
//
// Two passes:
//   • PATH rules  — match file/folder names in the archive.
//   • TEXT rules  — match inside the contents of a few key files (.gitignore,
//     package.json, README) where tools leave references (e.g. v0 keeps its
//     sandbox files gitignored, so the only trace is the .gitignore itself).

const PATH_RULES: { test: RegExp; label: string }[] = [
  { test: /(^|\/)\.cursor(\/|$)|(^|\/)\.cursor(rules|ignore)$/i, label: 'Cursor' },
  { test: /(^|\/)claude\.md$|(^|\/)\.claude(\/|$)/i,             label: 'Claude' },
  { test: /(^|\/)\.windsurf(rules)?(\/|$)/i,                     label: 'Windsurf' },
  { test: /(^|\/)\.aider/i,                                      label: 'Aider' },
  { test: /copilot-instructions/i,                              label: 'Copilot' },
  { test: /(^|\/)\.bolt(\/|$)/i,                                 label: 'Bolt' },
  { test: /(^|\/)\.replit$|(^|\/)replit\.nix$/i,                 label: 'Replit' },
  { test: /(^|\/)\.continue(rc)?(\/|$)/i,                        label: 'Continue' },
  { test: /(^|\/)agents\.md$/i,                                  label: 'AI agents' },
  // v0 footprints: sandbox runtime files, trash + snowflake dirs, .v0 / config
  { test: /(^|\/)__v0_|(^|\/)\.v0(-trash)?(\/|$)|(^|\/)\.snowflake(\/|$)|(^|\/)v0\.config\./i, label: 'v0' },
]

const TEXT_RULES: { test: RegExp; label: string }[] = [
  { test: /v0 sandbox|__v0_|\.v0-trash|v0\.dev/i, label: 'v0' },
  { test: /generated by cursor/i,                 label: 'Cursor' },
  { test: /\bclaude code\b/i,                      label: 'Claude' },
]

// Only these files are read for the text pass (kept small + cheap).
export const SIGNAL_TEXT_FILES = ['.gitignore', 'package.json', 'readme.md']

/**
 * Returns the sorted, de-duplicated list of AI tools whose footprints appear
 * in the archive — via file paths and (optionally) the contents of a few key files.
 */
export function scanAiSignals(paths: string[], texts: string[] = []): string[] {
  const found = new Set<string>()
  for (const p of paths) {
    for (const r of PATH_RULES) if (r.test.test(p)) found.add(r.label)
  }
  for (const t of texts) {
    for (const r of TEXT_RULES) if (r.test.test(t)) found.add(r.label)
  }
  return [...found].sort()
}
